# Generated by Django 4.1.7 on 2023-06-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_user_auctions_remove_user_bids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auctions.listings'),
        ),
    ]
