# Generated by Django 4.1.7 on 2023-06-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owner',
            new_name='auctions_owned',
        ),
    ]
