# Generated by Django 4.1.7 on 2023-06-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_owner_user_auctions_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='owner', to='auctions.bids'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='owner', to='auctions.comments'),
        ),
    ]
