# Generated by Django 4.1.7 on 2023-06-03 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_user_auctions_owned_user_auctions_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auctions_owned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='listings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listings'),
        ),
    ]
