# Generated by Django 4.1.7 on 2023-06-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_bids_user_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(default='no winner', max_length=64),
        ),
        migrations.AlterField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
        ),
    ]
