# Generated by Django 4.1.7 on 2023-06-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_closed_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bids',
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auctions.bids'),
        ),
    ]
