# Generated by Django 4.1.7 on 2023-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_comments_date_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
