# Generated by Django 4.1.7 on 2023-05-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='start_price',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
