# Generated by Django 4.1.7 on 2023-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listings_end_date_remove_listings_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(default='no image'),
        ),
    ]
