# Generated by Django 4.1.7 on 2023-05-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Title',
            new_name='title',
        ),
    ]
