# Generated by Django 4.1.7 on 2023-06-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_owner_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.listings'),
        ),
    ]
