# Generated by Django 4.1.7 on 2023-06-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_bids_user_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auctions_owned',
        ),
        migrations.AddField(
            model_name='user',
            name='auctions_owned',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.listings'),
        ),
    ]
