# Generated by Django 4.1.7 on 2023-06-21 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listings_winner_alter_bids_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='closed_listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('image', models.URLField(default='no image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('winner', models.CharField(default='no winner', max_length=64)),
            ],
        ),
    ]
