# Generated by Django 4.1.7 on 2023-06-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_user_bids_user_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auctions.bids'),
        ),
    ]
