# Generated by Django 4.1.7 on 2023-07-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_user_bids_bids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='closed_auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='old_listing', to='auctions.closed_listings'),
            preserve_default=False,
        ),
    ]
